#!/bin/bash
## Prototype of modli cli and mod manager.
## Written by John "Red" Richardson
## 15/01/25
#########REQUIREMENTS############
#-(Un)Install to stage files    #
#-Set and launch stage file     #
#-Different install engines     #
#################################
##modli [OPTIONS] [GAME] [FILE]	

if [[ ! -z $2 ]]; then
        GAME_ID=$2
fi
if [[ ! -z $3 ]]; then
        MOD=$3
        mod=${MOD%.*}
fi

#Set this to where you keep your games, such as your steam library.
GAMES=/mnt/games/Steam/steamapps/common
#Set this to where the modli data will be stored, such as mods
root=~/bin/data/modli

## Print help and exit
if [[ $1 = '-h' ]]; then
	. $root/help
	exit
fi
## Print managed games and exit
if [[ -z $GAME_ID && $1 = "-c" ]]; then
        echo "modli: Managed games and their IDs:"
        cat $root/gamecodes.txt
        exit
fi
## Manage or unmanage a game and exit
if [[ $1 = "--Manage" ]]; then
        . $root/Games/config
        exit
fi
##Get the game details
if [[ $GAME_ID -eq $Fallout4 ]]; then
        . $root/Games/"Fallout 4"/config
fi

## Pass the commands to the mod manager
. $ENGINE
