#!/bin/bash
## Prototype of modli cli and mod manager.
## Written by John "Red" Richardson
## 13/03/2025
##################USAGE##################
##modli [OPTIONS] [GAME] [FILE]	

##TODO:
#FIX
#THE #!@#ING
#IF STATEMENTS

#Set this to where you keep your games, such as your steam library.
GAMES=~/Games
#Set this to where the modli data will be stored, such as mods
root=~/git/modli/src
#Set this to where the downloaded mods will be found
DOWNLOADS=/mnt/games/mods

#get the passed vars
cmd=$1
if [[ ! -z "$2" ]]; then
	GAME_NAME="$2"
	GAMEPATH="$GAMES/$GAME_NAME"
fi

if [[ ! -z "$3" ]]; then
	MOD="$3"
fi

. src/modlifunctions

if [[ $cmd = "--Manage" || $cmd == "--Unmanage" ]]; then
        addOrRemoveGame 
	exit
fi

if [[ $cmd == "-h" ]]; then
	printHelp
	exit
fi

if [[ $cmd == "-c" ]]; then
	checkNewGames
	exit
fi

if [[ $cmd == "-C" ]]; then
	checkGames
	exit
fi

if [[ $cmd == "-m" ]]; then
	checkAvailableMods
	exit
fi

if [[ $cmd == "-M" ]]; then
	checkInstalledMods
	exit
fi
#Call the mod manager
. $root/ModManagers/"$GAME_NAME.mm"


